# Configuration file to determine the parameters for the S01 experiment
sequence: data/aic19-track1-mtmc-train/train/S03
od_model: models/object_detection/S03.pt
# feature_model: models/feature_extraction/S03.pt
# feature_d_threshold: 21.114258037647232