# Configuration file to determine the parameters for the S01 experiment
sequence: data/aic19-track1-mtmc-train/train/S04
od_model: models/object_detection/S04.pt
feature_model: models/feature_extraction/triplet_model_S0103.pt